### ISSUE TITLE
Remplacer flake8 + isort par Ruff

### ISSUE THREAD

**Issue by Erawpalassalg** [dataforgoodfr/Bloom#17]
@benoit-cty a [suggéré](https://github.com/dataforgoodfr/Bloom/pull/11#issuecomment-1441371772) que nous remplacions `flake8` + `isort` par [Ruff](https://github.com/charliermarsh/ruff-pre-commit) dans nos pre-commit hooks.

**Comment by SaboniAmine** [comment]
C'est effectivement très rapide!
J'ai pris en compte la plupart des règles proposées dans la documentation de Ruff, avec certaines exceptions sur les annotations de type qui me semblaient un peu pénibles / en conflit avec d'autres librairies. A voir si cela ne freine pas trop les ajouts futurs à la codebase, restons vigilants sur la nécessité des règles proposées.
