### ISSUE TITLE
Add tests + CI for each PR

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/Bloom#19]
=> quels tests ? simplement lancer le job et voir qu'on a bien X lignes (X correspondant au nombre de bateau)

=> quel framework ? pytest ?

**Comment by Erawpalassalg** [comment]
Allez, si ça vous va je prends celle-ci.

Je pense qu'un test d'intégration simple comme celui que tu proposes, pour commence, paraît pas mal. Je vais voir si d'autres idées me viennent en parcourant le code.

Les soucis mentionnés dans #18 pourraient être de bons candidats pour des tests aussi, une fois qu'une aura assuré la reproductibilité de ces bugs.

**Comment by SaboniAmine** [comment]
Je fais une première proposition via un workflow Github Actions, n'hésite pas à repasser dessus @Erawpalassalg !
