### ISSUE TITLE
[SPRINT] Créer le flag Aires Maritimes Protégées

### ISSUE THREAD

**Issue by TheoLvs** [dataforgoodfr/Bloom#46]
A quel point ça remonte déjà automatiquement maintenant que vous avez mis les données dans le PostGre @RonanMorgan @SaboniAmine ?

**Comment by SaboniAmine** [comment]
Pour cette alerte je suis sur le coup. Je te ping sur la PR dès qu'elle est prête.

**Comment by RonanMorgan** [comment]
cool. Tu penses que ce sera ok pour vendredi histoire que je jette un oeil ?

**Comment by TheoLvs** [comment]
Done

**Comment by TheoLvs** [comment]
Done dans la branche actuelle
