### ISSUE TITLE
Refactor data model "fichier plat"

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/Bloom#5]
Pour l'instant on a un gros fichier csv avec des lignes qui sont ajoutées au fur et à mesure.

Il faudrait découper ce fichier : 
- dans le temps : un fichier par mois ? par semaine ?
- par bateau ?
Les data scientist vont avoir besoin de travailler sur plusieurs bateaux en même temps donc ça peut être chiant de séparer par bateau mais  en même temps si demain on a 250 bateaux on va pas pouvoir tout garder dans le même fichier. A discuter avec l'équipe métier

Et refactorer le code python en conséquence.

**Comment by n-toussaint** [comment]
Alors recap' du besoin:

Analyse par bateau (sur tous les bateaux) à la granularité avec laquelle on arrive à avoir les données (toutes les 15 minutes) pour faire l'analyse en quasi temps réel pour Bloom.

2 cas d'usage:
- Récupérer les N points de la dernière journée (ou des dernières heures par exemple) pour comprendre une trajectoire en temps réel et détecter si ce bateau fraude
- Si fraude avérée, on aurait surement envie de revenir en arrière dans l'historique et comprendre si c'est un cas récurrent et comprendre l'histoire de ce bateau

Et la lecture de la donnée se fera surtout avec géopandas.

Du coup je propose de faire un fichier par bateau et d'avoir trois fonctions qui renverrait chacune un stream text IO . Un stream s'utilise de la même façon qu'un path avec (geo)pandas, donc super facile d'utilisation et ça nous donne la flexibilité d'avoir le découpage de fichier qu'on veut.

Les deux premières fonctions seront à utiliser pour les deux cas ci-dessus et la dernière étant une fonction de repli si jamais il y a un nouveau cas et qui permettrait d'appliquer n'importe quel filtre pour récupérer une partie de la donnée (pour ne pas ingérer une quantitée folle quand on aura un gros historique).

Ca donnerait quelque chose comme ça:

get_data_of_the_last_24h(source={"local", "s3"})
get_data_of_a_ship(ship_imo, source={"local", "s3"})
get_data(source={"local", "s3"}, filter: Callable)

Vous en pensez quoi ?

**Comment by RonanMorgan** [comment]
peut être un fonction très général avec en input une liste de bateau et un timestamp ? d'ailleurs elle pourrait être utilisé comme sous fonction pour les autres
