### ISSUE TITLE
Github Workflow management

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/Bloom#6]
Si vous avez besoin de droit spécifique sur git pour ce sujet, demandez moi :) 

- créer un hook pour éviter qu'on puisse push sur master
- créer des tags de priorisation (0 : urgent , 1 : medium, 2: long terme)
- demander à l'équipe si ils aimeraient avoir d'autres tags à implémenter
- ajouter un groupe de personne (ie notre équipe tech) qui serait automatiquement dans les reviewer des PR
- ajouter un système d'alerting (slack ou email) dès qu'une PR est en "in review" (peut être via gitAction ? ou tout simplement à voir dans les settings github)

**Comment by shadzic** [comment]
ajouter un système d'alerting (slack ou email) dès qu'une PR est en "in review" (peut être via gitAction ? ou tout simplement à voir dans les settings github) --> ça c'est possible avec l'intégration de l'app Github dans Slack - il faut juste que chaque personne de l'équipe tech s'y abonne - je peux voir pour mettre en place ça mais je suis pas sûre que ce soit la priorité

P.S.: ce serait top de mentionner ils ou elles pour l'équipe pour inclure les femmes :D merci :heart:

**Comment by RonanMorgan** [comment]
Disons que les grosses prio du moment sont déjà en cours de développement (sauf peut être celle ci : https://github.com/dataforgoodfr/Bloom/issues/4, je ne sais pas où en est @emmanue ) donc si t'as un peu de temps pour setup ça ça me va :)  

ps : on a déjà un channel bloom-tech, je peux t'y ajouter si tu le souhaites, en fonction de ce que tu me diras en mp sur ta préférence avec le pôle-tech de D4G

**Comment by RonanMorgan** [comment]
https://github.com/marketplace/actions/auto-assign-pr-and-request-review
